-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 09:18:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema board_db
-- -----------------------------------------------------
-- This is the schema for board database.
-- DROP SCHEMA IF EXISTS `board_db` ;

-- -----------------------------------------------------
-- Schema board_db
--
-- This is the schema for board database.
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `board_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- USE `board_db` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_seq` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(16) NOT NULL,
  `user_pwd` VARCHAR(40) NOT NULL,
  `user_name` VARCHAR(40) NULL,
  `nickname` VARCHAR(40) NULL,
  `email` VARCHAR(50) NULL,
  `user_rank` INT NULL,
  `joined_at` DATETIME NULL,
  PRIMARY KEY (`user_seq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `description` VARCHAR(500) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `content` VARCHAR(2000) NULL,
  `board_id` INT NOT NULL,
  `user_seq` INT NOT NULL,
  `view_cnt` INT NULL,
  `lft` INT NULL,
  `rgt` INT NULL,
  `depth` INT NULL,
  `created_at` DATETIME NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_board_idx` (`board_id` ASC) VISIBLE,
  INDEX `fk_article_user1_idx` (`user_seq` ASC) VISIBLE,
  CONSTRAINT `fk_article_board`
    FOREIGN KEY (`board_id`)
    REFERENCES `board` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(400) NULL,
  `user_seq` INT NOT NULL,
  `article_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  `lft` INT NULL,
  `rgt` INT NULL,
  `depth` INT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_article1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_comment_board1_idx` (`board_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_seq` ASC) VISIBLE,
  CONSTRAINT `fk_comment_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `board` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `originfile` VARCHAR(300) NULL,
  `savefolder` VARCHAR(300) NULL,
  `savefile` VARCHAR(300) NULL,
  `article_id` INT NOT NULL,
  INDEX `fk_file_article1_idx` (`article_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_file_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_like`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `article_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_seq` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_like_user1_idx` (`user_seq` ASC) VISIBLE,
  INDEX `fk_article_like_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_like_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_like_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment_like`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `comment_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_seq` INT NOT NULL,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_dislike_comment1_idx` (`comment_id` ASC) VISIBLE,
  INDEX `fk_comment_dislike_user1_idx` (`user_seq` ASC) VISIBLE,
  CONSTRAINT `fk_comment_dislike_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `comment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_dislike_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment_dislike`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `comment_dislike` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_seq` INT NOT NULL,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_dislike_user2_idx` (`user_seq` ASC) VISIBLE,
  INDEX `fk_comment_dislike_comment2_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_dislike_user2`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_dislike_comment2`
    FOREIGN KEY (`comment_id`)
    REFERENCES `comment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_dislike`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `article_dislike` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_seq` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_dislike_user1_idx` (`user_seq` ASC) VISIBLE,
  INDEX `fk_article_dislike_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_dislike_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `user` (`user_seq`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_dislike_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
